type IError = {
    code: string
    description: string
}

export enum IErrorCode {
    ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',
    ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
    CREDENTIALS_NOT_FOUND = 'CREDENTIALS_NOT_FOUND',
    DATE_OF_BIRTH_INVALID = 'DATE_OF_BIRTH_INVALID',
    EMAIL_INVALID = 'EMAIL_INVALID',
    FIRSTNAME_INVALID = 'FIRSTNAME_INVALID',
    FORBIDDEN = 'FORBIDDEN',
    GENDER_INVALID = 'GENDER_INVALID',
    INTERNAL = 'INTERNAL',
    LASTNAME_INVALID = 'LASTNAME_INVALID',
    PASSWORD_INVALID = 'PASSWORD_INVALID',
    UNKNOWN = 'UNKNOWN',
    USERNAME_INVALID = 'USERNAME_INVALID',
    USERNAME_NOT_OCCUPIED = 'USERNAME_NOT_OCCUPIED',
    USERNAME_OCCUPIED = 'USERNAME_OCCUPIED'
}

export default IError