version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    depends_on:
      - app-db
    environment:
        SPRING_CONFIG_LOCATION: '/config/'
        SPRING_DATASOURCE_URL: 'jdbc:postgresql://app-db/bayun-id-postgres'
        SPRING_DATASOURCE_USERNAME: 'user'
        SPRING_DATASOURCE_PASSWORD: 'password'
    volumes:
      - './config:/config'
    restart: 'unless-stopped'
  app-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: 'bayun-id-postgres'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
volumes:
  pgdata:


